CREATE EXTENSION pgcrypto;
CREATE TABLE jwt (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL ,
  key TEXT NOT NULL ,
  secret TEXT NOT NULL
);
